name: Run Notebook Daily

on:
  schedule:
    - cron: '0 12 * * *'   # Run daily at 12:00 UTC
  workflow_dispatch:        # Allow manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libraries
        run: |
          pip install notebook nbconvert papermill

      - name: Run notebook
        run: |
          papermill 2025.ipynb output.ipynb
